/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package microcreditbanking.classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricky Islam
 */
public class editAccount extends javax.swing.JFrame {

    /**
     * Creates new form openAccount
     */
    public editAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(1020, 470, 190, 30);

        jLabel18.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel18.setText("Current Loan: ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(820, 470, 190, 42);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(1020, 220, 190, 30);

        jLabel17.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel17.setText("Account Key: ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(830, 220, 171, 40);

        jButton3.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton3.setText("Generate Detail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1010, 70, 180, 50);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(830, 80, 160, 30);

        jLabel16.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel16.setText("Customer's Account Number: ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(450, 80, 380, 40);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(1020, 270, 190, 30);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(1020, 170, 190, 30);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(290, 270, 220, 30);

        jButton2.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jButton2.setText("<<Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(710, 550, 210, 80);

        jButton1.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jButton1.setText("Save Information >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(930, 550, 290, 80);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(1020, 420, 190, 30);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(1020, 370, 190, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(1020, 320, 190, 30);

        jLabel15.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel15.setText("Name Of First Nominee: ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(700, 370, 330, 42);

        jLabel14.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel14.setText("Current Balance: ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(790, 420, 220, 42);

        jLabel13.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel13.setText("Annual Income: ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(810, 320, 202, 42);

        jLabel12.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel12.setText("Account Type: ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(820, 170, 200, 42);

        jLabel11.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel11.setText("Sex: ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(950, 280, 60, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 490, 220, 150);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(290, 440, 220, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(290, 380, 220, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(290, 330, 220, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(290, 220, 220, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(290, 170, 220, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 120, 220, 30);

        jLabel10.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel10.setText("Full Address: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 500, 170, 42);

        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel9.setText("National ID Number: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 440, 269, 42);

        jLabel8.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel8.setText("Occupation: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 380, 160, 42);

        jLabel7.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel7.setText("Phone Number: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 330, 200, 42);

        jLabel6.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel6.setText("Date Of Birth: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 280, 190, 30);

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel5.setText("Customer Name: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 220, 220, 42);

        jLabel4.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel4.setText("Account Number: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 230, 42);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel3.setText("Current Date: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 110, 180, 42);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Edit Customer's Info.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 580, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcreditbanking/image/heat-wide.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String id = jTextField13.getText() ;
        
        
         String date  = jTextField1.getText() ;
         String ac = jTextField2.getText() ;
          String name = jTextField3.getText() ;
           String birth = jTextField10.getText() ;
            String phone = jTextField4.getText() ;
             String occupation = jTextField5.getText() ;
              String nid = jTextField6.getText() ;
               String address = jTextArea1.getText() ;
                String  sex = jTextField12.getText() ;
                String income = jTextField7.getText() ;
                   String nominee  = jTextField8.getText() ;
                    String balance = jTextField9.getText() ;
                    String type = jTextField11.getText() ;
                    String key = jTextField14.getText() ;
                    String loan = jTextField15.getText() ;
                
           
           try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

String query = "UPDATE  customer set cur_date = ?, account = ?, name = ? , b_day = ?, phone = ?, occupation = ?, nid = ? , address = ?, sex = ?, account_type = ? , account_key = ? , income = ? , nominee = ?, balance = ?, loan = ?  where account like '"+id+"' " ;

PreparedStatement p = null ;
 p = con.prepareStatement(query);

 p.setString (1,date ) ;
 p.setString (2, ac) ;
 p.setString (3, name) ;
 p.setString (4, birth ) ;
  p.setString (5, phone ) ;
 p.setString (6, occupation) ;
 p.setString (7, nid ) ;
 p.setString (8,address ) ;
  p.setString (9,sex ) ;
   p.setString (10,type ) ;
    p.setString (11,key ) ;

 p.setString (12, income) ;
 p.setString (13, nominee ) ;
  p.setString (14, balance ) ;
    p.setString (15, loan ) ;
  p.executeUpdate();
    
     JOptionPane.showMessageDialog(null,"Updated Successfully"); 
  con.close();
  
  
     jTextField1.setText(null);
           jTextField2.setText(null);
              jTextField3.setText(null);
                 jTextField5.setText(null);
                    jTextField7.setText(null);
                       jTextField8.setText(null);
                          jTextField4.setText(null);
                             jTextField9.setText(null);
                             jTextField6.setText(null);
                             jTextField11.setText(null);
                             jTextField12.setText(null);
                             jTextField10.setText(null);
                             jTextArea1.setText(null);
                             
                             
                             dispose () ;

}
                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
       
       
 
 
 
 
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
              jTextField1.setText(null);
           jTextField2.setText(null);
              jTextField3.setText(null);
                 jTextField5.setText(null);
                    jTextField7.setText(null);
                       jTextField8.setText(null);
                          jTextField4.setText(null);
                             jTextField9.setText(null);
                             jTextField6.setText(null);
                             jTextArea1.setText(null);
                             
                               jTextField10.setText(null);
                                 jTextField11.setText(null);
                                   jTextField12.setText(null);
                                     jTextField13.setText(null);
                                       jTextField14.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                 String id = jTextField13.getText() ;
  if (id.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Give A Valid Account Number !!! ");
  }      
  else {
      
           try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like '"+id+"' ");

if (rs.next()) {
         try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");
Statement stmt1=con.createStatement();
ResultSet rs1 = null ;
rs1 =  stmt1.executeQuery("SELECT * FROM customer  WHERE account like '"+id+"' ");

       
        while (rs1.next()) {
          String a  = rs.getString("cur_date") ;
              String b = rs.getString("account") ;
                  String c = rs.getString("name") ;
                      String d = rs.getString("b_day") ;
                          String e = rs.getString("phone") ;
                              String f  = rs.getString("occupation") ;
                                  String g = rs.getString("nid") ;
                                      String h  = rs.getString("address") ;
                                          String i = rs.getString("sex") ;
                                              String j = rs.getString("account_type") ;
                                              String jj = rs.getString("account_key") ;
                                                  String k  = rs.getString("income") ;
                                                      String l  = rs.getString("nominee") ;
                                                          String m  = rs.getString("balance") ;
                                                          String n  = rs.getString("loan") ;
                      
      jTextField1.setText(a);
           jTextField2.setText(b);
              jTextField10.setText(d);
                 jTextField4.setText(e);
                    jTextField6.setText(g);
                       jTextField7.setText(k);
                          jTextField8.setText(l);
                             jTextField9.setText(m);
                             jTextField5.setText(f);
                             jTextField3.setText(c);
                             jTextField12.setText(i);
                             jTextField11.setText(j);
                               jTextField15.setText(n);
                             jTextField14.setText(jj);
                             jTextArea1.setText(h);
   


             
   


}
 con.close();  
 
 
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
    
}
else {
    JOptionPane.showMessageDialog(null, " This Account Number Doesn't Exist !!! "); 
}


 con.close();      
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }   
       

  }  
      
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void editAccountFunction () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
