/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package microcreditbanking.classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricky Islam
 */
public class loanWindow extends javax.swing.JFrame {

    /**
     * Creates new form deposite
     */
    public loanWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(250, 470, 210, 40);

        jLabel12.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel12.setText("Year: ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 470, 80, 40);

        jComboBox3.setFont(new java.awt.Font("Arabic Typesetting", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(400, 540, 70, 40);

        jComboBox2.setFont(new java.awt.Font("Arabic Typesetting", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(310, 540, 80, 40);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(250, 540, 50, 40);

        jLabel11.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel11.setText("Payment Date: ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 530, 190, 42);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(250, 410, 210, 40);

        jLabel10.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel10.setText("Interest Rate: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 410, 180, 42);

        jButton3.setFont(new java.awt.Font("Arabic Typesetting", 1, 30)); // NOI18N
        jButton3.setText("Refresh Fields");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 620, 190, 50);

        jButton2.setFont(new java.awt.Font("Arabic Typesetting", 1, 30)); // NOI18N
        jButton2.setText("Save Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 620, 210, 50);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(250, 350, 210, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(250, 290, 210, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(250, 240, 210, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(250, 190, 210, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 140, 210, 40);

        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 1, 32)); // NOI18N
        jLabel9.setText(" Amount:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 350, 110, 38);

        jLabel7.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel7.setText("Current Balance: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 290, 220, 42);

        jLabel6.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel6.setText("Customer's Name: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 240, 240, 42);

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel5.setText("Account Number: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 190, 230, 40);

        jLabel4.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel4.setText("Date: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 140, 74, 40);

        jButton1.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton1.setText("Generate Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 70, 170, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(300, 70, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel3.setText("Enter Account Number: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 300, 40);

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 48)); // NOI18N
        jLabel2.setText("Loan Window");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 10, 320, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcreditbanking/image/loan.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 730, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
   String id = jTextField1.getText() ;
        
if (id.isEmpty()) {
    
    JOptionPane.showMessageDialog(null, "Fill Up The Fields Correctly !!! ");
}

else {
  try {
      
  Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like '"+id+"' ");

if (rs.next()) {
    
    
     try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt1=con.createStatement();
ResultSet rs1 = null ;
rs1 =  stmt1.executeQuery("SELECT * FROM customer  WHERE account like '%"+id+"%' ");

       
            while (rs1.next()) {
    
              String b = rs.getString("account") ;
                  String c = rs.getString("name") ;

                      String m  = rs.getString("balance") ;
                                                          
                                                          
                                                          
int day, month, year ;
int second, minute, hour ;
GregorianCalendar date = new  GregorianCalendar ( ) ;
day = date.get (Calendar.DAY_OF_MONTH) ;
month = date.get(Calendar.MONTH) ;
year = date.get(Calendar.YEAR) ;

second = date.get(Calendar.SECOND) ;
minute = date.get(Calendar.MINUTE) ;
hour = date.get(Calendar.HOUR) ;

String currentDate = (" " + day + " - " + (month+1) +" - " + year );

                                                         

    jTextField2.setText (currentDate) ;  
     jTextField3.setText (b) ;    
      jTextField4.setText (c) ;    
       jTextField5.setText (m) ;
 
   


}
 con1.close();  
 
 
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
        
    
}
else {
    JOptionPane.showMessageDialog(null, "Account Doesn't Exist !!! "); 
}
        
        
        
       
   } 
 catch (Exception e) {
      JOptionPane.showMessageDialog(null, " Error: "+e);
 }   
}    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String date = jTextField2.getText () ;
                 String ac = jTextField3.getText () ;
                         String name  = jTextField4.getText () ;
                          String balance = jTextField5.getText() ;
                    
                          String loan_amount = jTextField6.getText();
                          String interest = jTextField8.getText();
                          
        String bdate = (String) jComboBox1.getSelectedItem() ;
        String bmonth = (String) jComboBox2.getSelectedItem() ;
        String byear = (String) jComboBox3.getSelectedItem() ;
         
     String payment_date= (" " + bdate + " - " + bmonth +" - " + byear ); 
  String loan_year = jTextField9.getText() ;
  int pay_year = Integer.parseInt(loan_year) ;
  String final_amount ;
  float value = 0 ;
  float final_cost = 0 ;
  float a = 100 ;
  
  int amount = Integer.parseInt(loan_amount) ;
  int rate = Integer.parseInt(interest) ;
value = rate/a ;
 final_cost = (value*amount*pay_year) + amount ;
  final_amount = String.valueOf(final_cost) ;
  

   
        if (( loan_amount.isEmpty() || interest.isEmpty() || payment_date.isEmpty()))   {
          
        JOptionPane.showMessageDialog(null, "Please Fill Up All The Fields !!! "); 
      } 
      else {
        
   try {
      
  Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM loan  WHERE CUS_ACCOUNT_NO like'"+ac+"' ");

if (rs.next()) {
 
     JOptionPane.showMessageDialog(null, "Loan Already Taken !!! "); 
}
    
    else {
    
     try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt1=con1.createStatement();
stmt1.executeQuery ("INSERT INTO loan " + " VALUES ('"+ac+"', '"+name+"', '"+date+"', '"+amount+"',' "+interest+" ', '"+final_amount+"', '"+payment_date+"')");  

//stmt.executeQuery("insert into customer values (?,?,?,?,?,?,?,?,?,?,?,?,?) " );
//
//stmt.setString (1, date) ;
con1.close();

  JOptionPane.showMessageDialog(null, "Data Successfully Added To Database !!! ");

      jTextField1.setText(null);
           jTextField2.setText(null);
              jTextField3.setText(null);
                 jTextField5.setText(null);
       
                       jTextField8.setText(null);
                          jTextField4.setText(null);
                         
                             jTextField6.setText(null);
                      

  dispose () ;

}
                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
        
    
   
}
        
        
        
       
   } 
 catch (Exception e) {
      JOptionPane.showMessageDialog(null, " Error: "+e);
 }   
 
 
 
 
  
        
        }                                                        

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                jTextField1.setText (null) ;
          jTextField2.setText (null) ;
            jTextField3.setText (null) ;
              jTextField4.setText (null) ;  
                jTextField5.setText (null) ;
                jTextField6.setText (null) ;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void loanWindowFunction () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
