/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package microcreditbanking.classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricky Islam
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public logIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton2.setText("Exit");
        jPanel1.add(jButton2);
        jButton2.setBounds(730, 560, 110, 40);

        jButton1.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 560, 120, 40);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(590, 510, 250, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(590, 460, 250, 30);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel3.setText("Admin Password: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 510, 260, 42);

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel2.setText("Enter Admin Name: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 450, 360, 42);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcreditbanking/image/white_keyboard-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
                
        String id = jTextField1.getText();
        String pass = jPasswordField1.getText();

        if (id.length() == 0 || pass.length() == 0) {

            JOptionPane.showMessageDialog(null, "Please Fill Up The Fields Correctly !!! ");
        } else {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "shunno");

                Statement stmt = con.createStatement();
                ResultSet rs = null;
                rs = stmt.executeQuery("SELECT * FROM ADMINPANEL  WHERE USERNAME like '" + id + "' and PASSWORD like '" + pass + "' ");

                if (rs.next()) {
  


                    dispose();
 
                    
                    home homeObject = new home () ;
                    homeObject.homeFunction () ;


                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect User Name Or Password !!! ");
                }


                con.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, " Error: " + e);
            }


        }

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
          try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
stmt.executeQuery ("CREATE table \"ADMINPANEL\" (\n" +
"    \"USERNAME\"  VARCHAR2(4000),\n" +
"    \"PASSWORD\" VARCHAR2(4000)\n" +
")");  

con.close();

  //JOptionPane.showMessageDialog(null, "Database Created Successfully !!! ");


}
                catch(Exception e){
                    // JOptionPane.showMessageDialog(null, " Database Ready To Run !!!!  ");
}  
               
        
          
// -----------------------------------------------------------------------------------------------------------------------------------------------
          
     try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
stmt.executeQuery ("CREATE table \"CUSTOMER\" (\n" +
"    \"CUR_DATE\"   VARCHAR2(4000),\n" +
"    \"ACCOUNT\"    VARCHAR2(4000),\n" +
"    \"NAME\"       VARCHAR2(4000),\n" +
"    \"B_DAY\"      VARCHAR2(4000),\n" +
"    \"PHONE\"      VARCHAR2(4000),\n" +
"    \"OCCUPATION\" VARCHAR2(4000),\n" +
"    \"NID\"        VARCHAR2(4000),\n" +
"    \"ADDRESS\"    VARCHAR2(4000),\n" +
"    \"SEX\"        VARCHAR2(4000),\n" +
"    \"ACCOUNT_TYPE\"   VARCHAR2(4000),\n" +
"    \"ACCOUNT_KEY\"   VARCHAR2(4000),\n" +
"    \"INCOME\"     VARCHAR2(4000),\n" +
"    \"NOMINEE\"    VARCHAR2(4000),\n" +
"    \"BALANCE\"    VARCHAR2(4000),\n" +
"    \"LOAN\"    VARCHAR2(4000)\n" +
")");  

con.close();

  //JOptionPane.showMessageDialog(null, "Database Created Successfully !!! ");


}
                catch(Exception e){
                    // JOptionPane.showMessageDialog(null, " Database Ready To Run !!!!  ");
}
          
// -------------------------------------------------------------------------------------------------------------------------------------------------------
        try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
stmt.executeQuery ("CREATE table \"HISTORY\" (\n" +
"    \"CUSTOMER_ID\"      VARCHAR2(4000),\n" +
"    \"CUSTOMER_NAME\"    VARCHAR2(4000),\n" +
"    \"TRANSACTION_DATE\" VARCHAR2(4000),\n" +
"    \"TRANSACTION_TYPE\" VARCHAR2(4000),\n" +
"    \"TRANSACTION_MODE\" VARCHAR2(4000),\n" +
"    \"TRANSACTION_AMOUNT\" VARCHAR2(4000),\n" +
"    \"OLD_BALANCE\" VARCHAR2(4000),\n" +
"    \"FINAL_BALANCE\"    VARCHAR2(4000)\n" +
")");  

con.close();

  //JOptionPane.showMessageDialog(null, "Database Created Successfully !!! ");


}
                catch(Exception e){
                    // JOptionPane.showMessageDialog(null, " Database Ready To Run !!!!  ");
}
      
        
// -------------------------------------------------------------------------------------------------------------------------------------------------------
        try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
stmt.executeQuery ("CREATE table \"LOAN\" (\n" +

"    \"CUS_ACCOUNT_NO\"    VARCHAR2(4000),\n" +
"    \"CUS_NAME\" VARCHAR2(4000),\n" +
"    \"BORROW_DATE\" VARCHAR2(4000),\n" +
"    \"AMOUNT\" VARCHAR2(4000),\n" +
"    \"INTEREST\" VARCHAR2(4000),\n" +
"    \"FINAL_AMOUNT\" VARCHAR2(4000),\n" +

"    \"PAY_DATE\"    VARCHAR2(4000)\n" +
")");  

con.close();

  //JOptionPane.showMessageDialog(null, "Database Created Successfully !!! ");


}
                catch(Exception e){
                    // JOptionPane.showMessageDialog(null, " Database Ready To Run !!!!  ");
}

// -------------------------------------------------------------------------------------------------------------------------------------------------------
        try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
stmt.executeQuery ("CREATE table \"PAYMENT\" (\n" +

"    \"P_ACCOUNT_NO\"    VARCHAR2(4000),\n" +
"    \"P_CUS_NAME\" VARCHAR2(4000),\n" +
"    \"P_BORROW_DATE\" VARCHAR2(4000),\n" +
"    \"P_LOAN_AMOUNT\" VARCHAR2(4000),\n" +
"    \"P_DEADLINE\" VARCHAR2(4000),\n" +
 "    \"P_AMOUNT\" VARCHAR2(4000)\n" +


")");  

con.close();

  //JOptionPane.showMessageDialog(null, "Database Created Successfully !!! ");


}
                catch(Exception e){
                    // JOptionPane.showMessageDialog(null, " Database Ready To Run !!!!  ");
}
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
