/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package microcreditbanking.classes;

import java.awt.TextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricky Islam
 */
public class paymentWindow extends javax.swing.JFrame {

    /**
     * Creates new form deposite
     */
    public paymentWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(240, 490, 210, 40);

        jButton4.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton4.setText("Generate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(480, 490, 180, 40);

        jLabel10.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel10.setText("Still Paid : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 490, 140, 42);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(240, 430, 210, 40);

        jButton3.setFont(new java.awt.Font("Arabic Typesetting", 1, 30)); // NOI18N
        jButton3.setText("Refresh Fields");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 620, 190, 50);

        jButton2.setFont(new java.awt.Font("Arabic Typesetting", 1, 30)); // NOI18N
        jButton2.setText("Save Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 620, 210, 50);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(240, 550, 210, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(240, 370, 210, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 310, 210, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(240, 250, 210, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 190, 210, 40);

        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 1, 32)); // NOI18N
        jLabel9.setText("Payment Amount:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 550, 220, 38);

        jLabel8.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel8.setText("Payment Deadline: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 430, 250, 42);

        jLabel7.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel7.setText("Loan Amount:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 370, 200, 42);

        jLabel6.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel6.setText("Customer's Name: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 310, 240, 42);

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel5.setText("Account Number: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 250, 230, 40);

        jLabel4.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel4.setText("Date: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 190, 74, 40);

        jButton1.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton1.setText("Generate Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 70, 170, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(300, 70, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel3.setText("Enter Loan Number: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 270, 40);

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 48)); // NOI18N
        jLabel2.setText("Payment Window");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 10, 320, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcreditbanking/image/loan.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 730, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String id = jTextField1.getText() ;
        
if (id.isEmpty()) {
    
    JOptionPane.showMessageDialog(null, "Fill Up The Fields Correctly !!! ");
}

else {
  try {
      
  Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM loan WHERE cus_account_no like '"+id+"' ");

if (rs.next()) {
    
    
     try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt1=con.createStatement();
ResultSet rs1 = null ;
rs1 =  stmt1.executeQuery("SELECT * FROM customer  WHERE account like '%"+id+"%' ");

       
            while (rs1.next()) {
    
              String b = rs.getString("cus_account_no") ;
                  String c = rs.getString("cus_name") ;
                    String m  = rs.getString("final_amount") ;
                     String d = rs.getString("pay_date") ;
                                                          
                                                          
                                                          
int day, month, year ;
int second, minute, hour ;
GregorianCalendar date = new  GregorianCalendar ( ) ;
day = date.get (Calendar.DAY_OF_MONTH) ;
month = date.get(Calendar.MONTH) ;
year = date.get(Calendar.YEAR) ;

second = date.get(Calendar.SECOND) ;
minute = date.get(Calendar.MINUTE) ;
hour = date.get(Calendar.HOUR) ;

String currentDate = (" " + day + " - " + (month+1) +" - " + year );

                                                         

    jTextField2.setText (currentDate) ;  
     jTextField3.setText (b) ;    
      jTextField4.setText (c) ;    
       jTextField5.setText (m) ;
       jTextField7.setText (d) ;
 
   


}
 con1.close();  
 
 
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
        
    
}
else {
    JOptionPane.showMessageDialog(null, "Account Doesn't Exist !!! "); 
}
        
        
        
       
   } 
 catch (Exception e) {
      JOptionPane.showMessageDialog(null, " Error: "+e);
 }   
    
}
        
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String id = jTextField1.getText() ;
        String date = jTextField2.getText () ;
        String ac = jTextField3.getText () ;
         String name  = jTextField4.getText () ;
                          String amount = jTextField5.getText() ;
                          String last_payment = jTextField6.getText();
                          String deadline = jTextField7.getText();
                          String old = jTextField8.getText() ;                          
                    
                     double latest_payment = Float.parseFloat(last_payment) ;
                     double old_payment = Float.parseFloat(old) ;
                          
                     double sum = latest_payment + old_payment ;
                     
                     String payment_amount = String.valueOf(sum) ;
                  System.out.println ("ricky")   ;

                          
       
        if ((last_payment.isEmpty()))   {
          
        JOptionPane.showMessageDialog(null, "Please Fill Up All The Fields !!! "); 
      } 
      else {
        

             try {
      
  Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM payment  WHERE p_account_no like'"+id+"' ");

if (rs.next()) {
    
    try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con1 =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

String query = "UPDATE  payment set  P_CUS_NAME = ?, P_BORROW_DATE = ? , P_LOAN_AMOUNT = ?, P_DEADLINE = ?, P_AMOUNT = ? where p_account_no like '"+id+"' " ;
PreparedStatement p1 = null ;
 p1 = con1.prepareStatement(query);

//Statement stmt1=con.createStatement();
//ResultSet rs1 = null ;
//rs1 =  stmt1.executeQuery("SELECT * FROM payment  WHERE p_amount like '"+id+"' ");
//
//       
//        while (rs1.next()) {
//          String a  = rs.getString("p_amount") ;
//          float variable = Integer.parseInt(a) ;
//          float given_amount = Integer.parseInt(payment_amount) ;
//          float sum  = given_amount + variable ;
//          
//          String final_payment_amount = String.valueOf(sum) ;
//          
//
//          
//        }

 
 
 
           p1.setString (1, name) ;
 p1.setString (2, date) ;
 p1.setString (3, amount ) ;
  p1.setString (4, deadline ) ;
 p1.setString (5,payment_amount) ;
  
  p1.executeUpdate();
 



    
     JOptionPane.showMessageDialog(null,"Updated Successfully"); 
  con1.close();
  
  
     jTextField1.setText(null);
           jTextField2.setText(null);
              jTextField3.setText(null);
                 jTextField5.setText(null);
                    jTextField7.setText(null);
               
                          jTextField4.setText(null);
                    
                             jTextField6.setText(null);
                        
                             
                             
                             dispose () ;

}
                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
       
       
 
    
    
}
else {
    
     try {

stmt.executeQuery ("INSERT INTO payment " + " VALUES ('"+id+"', '"+name+"', '"+date+"', '"+amount+"',' "+deadline+" ', '"+payment_amount+"')");  

//stmt.executeQuery("insert into customer values (?,?,?,?,?,?,?,?,?,?,?,?,?) " );
//
//stmt.setString (1, date) ;
con.close();

  JOptionPane.showMessageDialog(null, "Data Successfully Added To Database !!! ");

      jTextField1.setText(null);
           jTextField2.setText(null);
              jTextField3.setText(null);
                 jTextField5.setText(null);

                          jTextField4.setText(null);
                         
                             jTextField6.setText(null);
                      

  dispose () ;

}
                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
    
//    
//    JOptionPane.showMessageDialog(null, "Account Doesn't Exist !!! "); 
}
        
        
        
       
   } 
 catch (Exception e) {
      JOptionPane.showMessageDialog(null, " Error: "+e);
 }   
            
        
        
        }                                                        

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                jTextField1.setText (null) ;
          jTextField2.setText (null) ;
            jTextField3.setText (null) ;
              jTextField4.setText (null) ;  
                jTextField5.setText (null) ;
                jTextField6.setText (null) ;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
 String id ;
 id = jTextField1.getText() ;
 
 
    try {
        
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");
Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM payment  WHERE p_account_no like '"+id+"' ");

       
        while (rs.next()) {
          String a  = rs.getString("p_amount") ;

                                                          
jTextField8.setText(a);
  

}
 con.close();  
 
 
        
          }
    
    catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   } 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void paymentWindowFunction () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
