/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package microcreditbanking.classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricky Islam
 */
public class transfer extends javax.swing.JFrame {

    /**
     * Creates new form deposite
     */
    public transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jButton4.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton4.setText("Check Availablity");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(490, 450, 170, 40);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(250, 450, 210, 40);

        jButton3.setFont(new java.awt.Font("Arabic Typesetting", 1, 30)); // NOI18N
        jButton3.setText("Refresh Fields");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 580, 190, 50);

        jButton2.setFont(new java.awt.Font("Arabic Typesetting", 1, 30)); // NOI18N
        jButton2.setText("Save Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(250, 580, 210, 50);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(250, 500, 210, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(250, 400, 210, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(250, 350, 210, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(250, 300, 210, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 250, 210, 40);

        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 1, 32)); // NOI18N
        jLabel9.setText(" Amount:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 500, 110, 38);

        jLabel8.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel8.setText("Destination A/C : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 450, 229, 42);

        jLabel7.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel7.setText("Current Balance: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 400, 220, 42);

        jLabel6.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel6.setText("Customer's Name: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 350, 240, 42);

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel5.setText("Account Number: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 300, 230, 40);

        jLabel4.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel4.setText("Date: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 250, 74, 40);

        jButton1.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jButton1.setText("Generate Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 70, 170, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 70, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel3.setText("Enter Account Number: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 300, 40);

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 48)); // NOI18N
        jLabel2.setText("Transfer Window");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 10, 320, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcreditbanking/image/ttt.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 730, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String id = jTextField1.getText() ;
        
if (id.isEmpty()) {
    
    JOptionPane.showMessageDialog(null, "Fill Up The Fields Correctly !!! ");
}

else {
  try {
      
  Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like'"+id+"' ");

if (rs.next()) {
    
    
     try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt1=con.createStatement();
ResultSet rs1 = null ;
rs1 =  stmt1.executeQuery("SELECT * FROM customer  WHERE account like '%"+id+"%' ");

       
            while (rs1.next()) {
    
              String b = rs.getString("account") ;
                  String c = rs.getString("name") ;

                      String m  = rs.getString("balance") ;
                                                          
                                                          
                                                          
int day, month, year ;
int second, minute, hour ;
GregorianCalendar date = new  GregorianCalendar ( ) ;
day = date.get (Calendar.DAY_OF_MONTH) ;
month = date.get(Calendar.MONTH) ;
year = date.get(Calendar.YEAR) ;

second = date.get(Calendar.SECOND) ;
minute = date.get(Calendar.MINUTE) ;
hour = date.get(Calendar.HOUR) ;

String currentDate = (" " + day + " - " + (month+1) +" - " + year );

                                                         

    jTextField2.setText (currentDate) ;  
     jTextField3.setText (b) ;    
      jTextField4.setText (c) ;    
       jTextField5.setText (m) ;
 
   


}
 con1.close();  
 
 
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
        
    
}
else {
    JOptionPane.showMessageDialog(null, "Account Doesn't Exist !!! "); 
}
        
        
        
       
   } 
 catch (Exception e) {
      JOptionPane.showMessageDialog(null, " Error: "+e);
 }   
    
}
        
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String date = jTextField2.getText () ;
                 String ac = jTextField3.getText () ;
                         String name  = jTextField4.getText () ;
                                 String type  = "Transfer" ;
                                       //  String mode = (String) jComboBox1.getSelectedItem() ;
                                          String old_balance = jTextField5.getText() ;
                                                         String amount = jTextField6.getText() ;
 String id = jTextField3.getText() ;
  String id2 = jTextField7.getText() ;
        
        try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
Statement stmt22=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like '%"+id+"%' ");
ResultSet rs1 = null ;
rs1 = stmt22.executeQuery("SELECT * FROM customer  WHERE account like '%"+id2+"%' ") ;

       
            while (rs.next()) {

                 String m  = rs.getString("balance") ;

            int old_balance11 = Integer.parseInt(m) ;
            String string_amount = jTextField6.getText() ;
            int int_amount = Integer.parseInt(string_amount) ;
            int new_balance = old_balance11 - int_amount ;
            String new_balance_string = String.valueOf(new_balance) ;
            
            
            while (rs1.next()) {
                String n = rs1.getString("balance") ;
            
                     int old_balance22 = Integer.parseInt(n) ;
            String string_amount22 = jTextField6.getText() ;
            int int_amount22 = Integer.parseInt(string_amount22) ;
            int new_balance22 = old_balance22 + int_amount22 ;
            String new_balance_string22 = String.valueOf(new_balance22) ;    
            
 if ( int_amount > old_balance11 ) {
     
     JOptionPane.showMessageDialog(null, "Transaction Not Possible !!! ");
 }
 
 else {
                 
     try {
         
    
     
     String query =("UPDATE  customer set balance = ?  where account like '%"+id+"%' ");   
         String query22 =("UPDATE  customer set balance = ?  where account like '%"+id2+"%' "); 
    PreparedStatement p = null ;
        PreparedStatement p22 = null ;
 p = con.prepareStatement(query); 
    p.setString (1,new_balance_string ) ;
     p.executeUpdate();
     
      p22 = con.prepareStatement(query22); 
    p22.setString (1,new_balance_string22 ) ;
     p22.executeUpdate();
     
   JOptionPane.showMessageDialog(null, "Transaction Completed !!! ");
   System.out.println(new_balance_string);
     System.out.println(new_balance_string22);
     System.out.println(new_balance);
     System.out.println(new_balance22);
        
   jTextField1.setText (null) ;
          jTextField2.setText (null) ;
            jTextField3.setText (null) ;
              jTextField4.setText (null) ;  
                jTextField5.setText (null) ;
                jTextField6.setText (null) ;
                 jTextField7.setText (null) ;
      }
     
     
     catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
     
     
     
     
     
     
     
     
     
     
     
 }
     
            }
     }
 con.close();  
 
 
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
    
   
         
   
                                         
       try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like '%"+id+"%' ");

       
            while (rs.next()) {

                                                          String final_balance  = rs.getString("balance") ;
            }
 con.close();
       }
       catch(Exception e){
       }                           
         
     try {
         
        
         
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();

ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like '%"+id+"%' ");

      String m = null ; 
            while (rs.next()) {

            m  = rs.getString("balance") ;
           
          }
String mode = "Cash" ;


stmt.executeQuery ("INSERT INTO history " + " VALUES ('"+ac+"', '"+name+"', '"+date+"', '"+type+"',' "+mode+" ', '"+amount+"', '"+old_balance+"', '"+m+"')");  


con.close();

 
     }
                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }       
          
                                                         
                                                         
  dispose () ;                                                       

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                jTextField1.setText (null) ;
          jTextField2.setText (null) ;
            jTextField3.setText (null) ;
              jTextField4.setText (null) ;  
                jTextField5.setText (null) ;
                jTextField6.setText (null) ;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
           String id = jTextField7.getText( ) ;
//          
//          try {
//Class.forName("oracle.jdbc.driver.OracleDriver");
//Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");
//
////Statement stmt=con.createStatement();
////ResultSet rs = null ;
////String b ;
////rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account = ? " +id );
//
//PreparedStatement st = con.prepareStatement("select * from customer where account = ? ") ;
//st.setString(1, id);
//
//ResultSet rs = st.executeQuery() ;
//       
//            while (rs.next()) {
//
//          String  b = rs.getString("account") ;
//              
////              int database_account = Integer.parseInt(b) ;
////              int database_id = Integer.parseInt(id) ;
//                 
//             if (id.matches(b)) {
//                 JOptionPane.showMessageDialog(null, "Destination Account Avilable !!!");
//                 System.out.println("Y");
//            
//             } 
//             
//             else {
//                 JOptionPane.showMessageDialog(null, "Destination Account Not Avilable !!!"); 
//                  System.out.println("n");
//             }
//
//   
//
//
//}
// con.close();
//          }
//
//                catch(Exception e){
//                     JOptionPane.showMessageDialog(null, " Error: "+e);
//                   }
//        
        

        
   if (id.length() == 0) {
       
        JOptionPane.showMessageDialog(null, "Please Fill Up The Fields Correctly !!! ");
   }    
   else {
        try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","shunno");

Statement stmt=con.createStatement();
ResultSet rs = null ;
rs =  stmt.executeQuery("SELECT * FROM customer  WHERE account like '"+id+"'  ");

if (rs.next()) {
     JOptionPane.showMessageDialog(null, "Account Is Available !!! "); 
   
    
    
}
else {
    JOptionPane.showMessageDialog(null, "Destination Account Not Avilable !!! "); 
}


 con.close();      
        
          }

                catch(Exception e){
                     JOptionPane.showMessageDialog(null, " Error: "+e);
                   }
            
       
   } 
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void transferFunction() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
